// get all
GET http://localhost:3001/api/persons
###
// server datetime
GET http://localhost:3001/info
### 
// get 1 person
GET http://localhost:3001/api/persons/654fddb76e04701d4e124b58
### 
// delete 1 person
DELETE http://localhost:3001/api/persons
content-type: application/json

{
  "id": "6550133122720a31e7a270fa"
}
###
// add 1 person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Sergio Perez",
  "number": "655013cb46f79fc62d083fec"
}

###
//modify 1 person
PUT http://localhost:3001/api/persons
Content-Type: application/json

{
  "id": "655074769e4242dfcf352f85",
  "newnumber": "123-111-1111111111"
}

###
// unknown endpoint
GET http://localhost:3001/unknown